apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  annotations:
    messaging.knative.dev/creator: opentlc-mgr
    messaging.knative.dev/lastModifier: opentlc-mgr
  name: channel-user-registration-consumer
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: Channel
    name: channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: user-registration-consumer
